language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm
        - php: nightly

before_script:
    - composer install --dev --no-interaction

after_script:
  - php vendor/bin/coveralls -v

script:
    - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml