name: Testing

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
      - name: PHP_CodeSniffer
        run: |
          cd ${GITHUB_WORKSPACE}
          ./vendor/bin/phpcs --standard=./phpcs.xml
