name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install Composer dependencies
        uses: php-actions/composer@v6

      - name: PHP_CodeSniffer
        run: |
          cd ${GITHUB_WORKSPACE}
          ./vendor/bin/phpcs --standard=./phpcs.xml
