name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Create releasee zip
        run: |
            make clean
            make install-npm
            make build
            make release

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "chriswiegman-theme.${{ env.RELEASE_VERSION }}.zip"
          bodyFile: ".changes/${{ env.RELEASE_VERSION }}.md"
