name: Playwright Tests

on:
  push:
    branches: [ main, canary ]
  pull_request:
    branches: [ main, canary ]

jobs:
  playwright-test:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout project
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install Node dependencies
      run: npm ci

    - name: Build CSS and JS
      run: npm run build

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Start WordPress Environment and activate theme
      run: |
        npx wp-env start
        npx wp-env run cli wp theme activate chriswiegman-theme

    - name: Run Playwright tests
      run: npm run test

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: e2e-report
        path: artifacts/test_results/
        retention-days: 30
